version: '3'

services:
  trytond:
    build:
      context: ./trytond
    container_name: tinta-trytond
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - data:/var/lib/trytond/db
    env_file:
      - variables.env

  # trytond-cron:
  #   build:
  #     context: ./trytond
  #   container_name: trytond-cron
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #     - trytond
  #   networks:
  #     - default
  #   volumes:
  #     -data:/var/lib/trytond/db
  #   env_file:
  #     - variables.env

  # tryton-update:
  #   build:
  #     context: ./trytond
  #   command: sh -c "sleep 10 && trytond-admin -d tryton --all --activate-dependencies -v && tail -f /dev/null"
  #   restart: "no"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - default
  #   volumes:
  #     - data:/var/lib/trytond/db
  #   env_file:
  #     - variables.env

  postgres:
    image: postgres:12-alpine
    container_name: tinta-postgres
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - variables.env

networks:
  default:

volumes:
  data:
  postgres-data:
