version: '3'

services:
  trytond:
    image: tinta
    build:
      context: ./trytond
    container_name: tinta-trytond
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - data:/var/lib/trytond/db
    env_file:
      - variables.env

  trytond-cron:
    image: tinta
    container_name: tinta-cron
    command: sh -c "/run-cron.sh"
    restart: unless-stopped
    depends_on:
      - postgres
      - trytond
    networks:
      - default
    volumes:
      - data:/var/lib/trytond/db
    env_file:
      - variables.env

  trytond-worker:
    image: tinta
    container_name: tinta-worker
    command: sh -c "/run-worker.sh"
    restart: unless-stopped
    depends_on:
      - postgres
      - trytond
    networks:
      - default
    volumes:
      - data:/var/lib/trytond/db
    env_file:
      - variables.env

  postgres:
    image: postgres:12-alpine
    container_name: tinta-postgres
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - variables.env

  web:
    image: tinta
    container_name: tinta-web
    command: sh -c "uwsgi --ini /uwsgi-flask.conf"
    restart: unless-stopped
    depends_on:
      - postgres
      - trytond
    networks:
      - default
    volumes:
      - data:/var/lib/trytond/db
    env_file:
      - variables.env

networks:
  default:

volumes:
  data:
  postgres-data:
